FIX: await isn't allowed in non-async function
Failed to compile.

./app/layout.tsx
Error:   x await isn't allowed in non-async function
    ,-[/home/ubuntu/rl-swarm/modal-login/app/layout.tsx:27:1]
 24 |     config,
 25 |     headers().get("cookie") ?? undefined,
 26 |   );*/
 27 | const headerList = await headers();
    :                    ^^^^^
 28 | const initialState = cookieToInitialState(
 29 |   config,
 30 |   headerList.get("cookie") ?? undefined,
    `----

Caused by:
    Syntax Error

Import trace for requested module:
./app/layout.tsx